import Navbar from "@/components/Header"
import "../../styles/globals.css"

export const metadata = {
  title: "Auction",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Navbar />
      {children}
    </>
  )
}
