import { Inter } from "next/font/google"
import Head from "next/head"
import Image from "next/image"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <div className="h-screen bg-neutral-200">
        <div className="w-full max-w-[560px] h-full bg-neutral-100 border-x border-x-neutral-500 mx-auto">
          <div className="p-6 border-b border-b-neutral-500">
            <div>
              <div>
                <div className="flex">
                  <div>
                    <Image
                      src="https://avatars.githubusercontent.com/u/121525239?v=4"
                      alt="Foto de Vitor Markis"
                      width={56}
                      height={56}
                      className="rounded-full border border-black shrink-0 object-cover"
                    />
                  </div>
                  <div className="leading-4 ml-3">
                    <p className="text-lg text-neutral-800">Vitor Markis</p>
                    <span className="text-sm text-neutral-500">há 20 minutos</span>
                  </div>
                  <div className="ml-auto flex">
                    <p className="">...</p>
                  </div>
                </div>
                <div className="mt-3">
                  <p>
                    texto desse novo post texto desse novo post texto desse novo post texto desse novo post
                  </p>
                </div>
                <div className="mt-3 rounded-lg flex flex-col border border-black overflow-hidden cursor-pointer">
                  <div className="flex">
                    <img
                      alt="Foto do post"
                      src="https://img.olx.com.br/images/73/730396125379230.jpg"
                      className="object-cover w-full h-72 border-r border-r-black"
                    />
                    <img
                      alt="Foto do post"
                      src="https://img.olx.com.br/images/73/731333607460976.jpg"
                      className="object-cover w-full h-72"
                    />
                  </div>
                  <div className="p-2 bg-neutral-800">
                    <h2 className="text-white font-semibold">iPhone 8 semi novo s/fone de ouvido</h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
