import "../styles/globals.css"
import { Providers } from "./providers"

import { Roboto } from "next/font/google"
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
})

export const metadata = {
  title: "Auction",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="overflow-y-hidden">
        <Providers>
          <div className={`min-h-screen flex flex-col ${roboto.className}`}>{children}</div>
          <div id="portal"></div>
        </Providers>
      </body>
    </html>
  )
}
